### ISSUE TITLE
support handleMessage ？？？

### ISSUE THREAD

**Issue by 79144876** [badoo/android-weak-handler#3]
Hi.it support handleMessage or not  like this?
```
    Handler handlerButtonToggleAction = new Handler() {
        public void handleMessage(Message msg) {
            switch (msg.what) {
                case 1:
                    MediaArticle article = (MediaArticle) msg.obj;
                    if (article.isCached()) {
                        showArticleActionDialog(article);
                    } else {
                        toggleArticleCacheStatus(article);
                    }
                    break;
            }
        }
    };
```
In my project. i have a main handler in activity to update ui by message tag.
Thanks.

**Comment by dmitry-voronkevich** [comment]
Hi,

The only change to your code would be initialized handler with callback:

    Handler handlerButtonToggleAction = new Handler(new Callback() {
        ...
    });

**Comment by 79144876** [comment]
Ok? i will try it latter.
Thanks.

**Comment by sirvon** [comment]
How would I get it to work with this setup:

```java
class MessageHandler extends WeakHandler {

        public MessageHandler(Looper looper) {
            super(looper);
        }

        @DebugLog
        @Override
        public void handleMessage(Message msg) {
            super.handleMessage(msg);
            try {
                String m = msg.getData().getString("message");

...


}
```

**Comment by dmitry-voronkevich** [comment]
Hi, is it possible to convert your Handler class to Callback class and then pass it as a constructor for WeakHandler?

**Comment by sirvon** [comment]
is that the only option...can you give an example of doing that....

That class is an inner class to use the callback option I would have to arrange code...

But if thats the only way, I want to use this WeakHandler for safety...

**Comment by dmitry-voronkevich** [comment]
This is only one option, otherwise you will keep hard reference to outer
class.

**Comment by MIkeeJY** [comment]
@dmitry-voronkevich just like this??
       WeakHandler mhandler = new WeakHandler(new Handler.Callback() {

            @Override
            public boolean handleMessage(Message msg) {
                return false;
            }
        });

**Comment by dmitry-voronkevich** [comment]
@MIkeeJY exactly :)

**Comment by joedan0104** [comment]
> How would I get it to work with this setup:
> 
> ```java
> class MessageHandler extends WeakHandler {
> 
>         public MessageHandler(Looper looper) {
>             super(looper);
>         }
> 
>         @DebugLog
>         @Override
>         public void handleMessage(Message msg) {
>             super.handleMessage(msg);
>             try {
>                 String m = msg.getData().getString("message");
> 
> ...
> 
> 
> }
> ```

I also like this
