### ISSUE TITLE
What's the different between this and normal handler?

### ISSUE THREAD

**Issue by tinybright** [badoo/android-weak-handler#5]
Normal handler and this handler all will be recycled after message is dealed.

**Comment by dmitry-voronkevich** [comment]
Hi,

You are completely right. Once message being executed it is deleted then. However message in the queue for Handler will remain there altogether with hard reference to the object inside.
Please read full article here: https://techblog.badoo.com/blog/2014/08/28/android-handler-memory-leaks/
